DROP TABLE IF EXISTS quizzes;

CREATE TABLE quizzes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    topic TEXT NOT NULL,
    displayContent TEXT NOT NULL,
);